/**
 * Contract utility — loads the deployed contract address and ABI
 * The deploy script auto-saves this config to ../contracts/CertificateVerification.json
 */

import { ethers } from 'ethers';

// This file is auto-generated by scripts/deploy.js after deployment.
// If it doesn't exist yet, you need to deploy the contract first.
let contractConfig = null;

try {
  contractConfig = await import('../contracts/CertificateVerification.json');
} catch (e) {
  console.warn('Contract config not found. Please deploy the contract first.');
}

/**
 * Get a read-only contract instance (no signer needed)
 */
export function getReadOnlyContract(provider) {
  if (!contractConfig) {
    throw new Error('Contract not deployed. Run: npx hardhat run scripts/deploy.js --network localhost');
  }
  return new ethers.Contract(contractConfig.address, contractConfig.abi, provider);
}

/**
 * Get a writable contract instance (signer required for transactions)
 */
export function getContract(signer) {
  if (!contractConfig) {
    throw new Error('Contract not deployed. Run: npx hardhat run scripts/deploy.js --network localhost');
  }
  return new ethers.Contract(contractConfig.address, contractConfig.abi, signer);
}

/**
 * Get the contract address
 */
export function getContractAddress() {
  return contractConfig?.address || null;
}

/**
 * Check if contract has been deployed (config file exists)
 */
export function isContractDeployed() {
  return contractConfig !== null && contractConfig.address !== undefined;
}
